#!/bin/env bash

#install paru
if ! type "paru" > /dev/null; then
    doas pacman -S base-devel #i often forget about this
    pushd -q /tmp || exit 1
    git clone https://aur.archlinux.org/paru.git || exit 1
    pushd -q paru || exit 1
    makepkg -si --noconfirm
    popd -q
    popd -q
fi

#use paru to install everything from package list
paru -S - < $HOME/.config/yadm/pkglist
doas chsh -s "$(which zsh)" "$(whoami)"

yadm submodule update --init --recursive
