#!/bin/bash
killall -q lemonbar

if [[ "$(uname -n)" == "kucing" ]]
then
	conky -c "$HOME/.config/conky/kucing.conf" | lemonbar \
		-f "-xos4-terminus-medium-r-normal--12-120-*-*-*-*-*-*" \
		-B "#2E3440" \
		-F "#ECEFF4" \
		| sh
else
	conky | lemonbar \
		-f "-xos4-terminus-medium-r-normal--12-120-*-*-*-*-*-*" \
		-B "#2E3440" \
		-F "#ECEFF4" \
		| sh
fi
