#!/bin/bash
sxhkd &

~/.config/polybar/launch.sh &

if [[ $(hostname) == "kucing" ]]
then
	bspc monitor DVI-I-1 -d I II III IV V
	bspc monitor HDMI-1 -d VI VII VIII IX X
else
	bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

bspc rule -a Emacs state=tiled
