#!/bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &

#~/.config/polybar/launch.sh &
~/.config/lemonbar/lb-conky &

if [[ $(uname -n) == "kucing" ]]
then
	bspc monitor DVI-I-1 -d I II III IV V
	bspc monitor HDMI-1 -d VI VII VIII IX X
else
	bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X
fi

bspc config window_gap 0

bspc rule -a Emacs state=tiled #for some reason, emacs likes to start floating
bspc rule -a feh state=floating
bspc rule -a mpv state=floating sticky=on rectangle=426x240+1450+800

xsetroot -cursor_name left_ptr &
#make lemonbar stop being above fullscreen applications
#making it work for multiple monitors
xdo id -n root | awk '{system("xdo above -t " $1 " $(xdo id -a bar | head -" NR " | tail -1)")}'

#starting some Nice Programs
bspc rule -a URxvt -o desktop='^1'; urxvt &
bspc rule -a qutebrowser -o desktop='^2'; qutebrowser &
bspc rule -a Emacs -o desktop='^3'; emacsclient -c &
